### ISSUE TITLE
Conditional sampling on multiple features

### ISSUE THREAD

**Issue by dionman** [kathrinse/be_great#10]
Hello,
How can the sampling operation be conditioned on more than one features?

**Comment by tleemann** [comment]
Hi, sorry for the late reply. We have an experimental imputation interface in the branch ``imputation_interface`` which features an ``impute`` function in the interface, where you can conditional each sample on individual values.

https://github.com/kathrinse/be_great/tree/imputation_interface

Hope this helps

Tobias

**Comment by AjayTalati76** [comment]
Hi, can the impute function be used to recreate figure 8 from  the paper -  
![image](https://github.com/user-attachments/assets/1cd1638b-212d-489f-bbc6-5f2a576c6bd5)
