### ISSUE TITLE
Sample failed because of list index out of range

### ISSUE THREAD

**Issue by vinay-k12** [kathrinse/be_great#11]
Hi, 

I'm training a dataset with over and above 91 columns and has both categorical and numerical values. I trained with 10 epochs and tried to do sampling. But the sampling is failed because of this error - "list index out of range" 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/19322429/216009380-ffec6c37-13f7-40ce-b4ae-ad28d83f69f7.png">

**Comment by sergulaydore** [comment]
Did you figure this out @vinay-k12 ? I am having the same issue.

**Comment by unnir** [comment]
the new version should give a more user-friendly error message.
