### ISSUE TITLE
TypeError: '<' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by Bezdarnost** [kathrinse/be_great#25]
![image](https://github.com/kathrinse/be_great/assets/67479108/357af636-d519-4652-8886-ee21b20aa1d0)
![image](https://github.com/kathrinse/be_great/assets/67479108/c7ca1318-84b7-4721-8447-34f0403c8592)

how to fix?

**Comment by unnir** [comment]
Can't reproduce the error. It works great on colab. 
Have you used the code from the readme page?

```py
from be_great import GReaT
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True).frame

model = GReaT(llm='distilgpt2', batch_size=32, epochs=50)
model.fit(data)
synthetic_data = model.sample(n_samples=100)
```

If yes, please try to reinstall the be_great and restart your jupyter notebook. Plus, I suggest deleting files checkpoints. 

Hope it helps.

**Comment by unnir** [comment]
also: https://github.com/kathrinse/be_great/issues/12

**Comment by Bezdarnost** [comment]
> 

oh, training started, thank you a lot(honestly, I've tried a couple of reinstallations)

**Comment by unnir** [comment]
happy to read it, if you have more questions, do not hesitate to ask :)
