### ISSUE TITLE
How can we use other LMs other than distilgpt2 and gpt2

### ISSUE THREAD

**Issue by rklohana** [kathrinse/be_great#26]

**Comment by unnir** [comment]
Hi, 

What kind of models do you want to use?

**Comment by rklohana** [comment]
I want to use something like Falcon 7b,
Can you tell me what hyper-parameters I will need to adjust, and what change modules other than the trainer?

**Comment by Travisma2233** [comment]
I have the same problem, is it possible to use GPT3 in this model

**Comment by Travisma2233** [comment]
I have the same problem. If it is possible to use GPT3 in this model ?

**Comment by unnir** [comment]
@Travisma2233 

In general, replacing the model name within the HuggingFace library in GReaT's initialization is typically all you need. For example:
```py
model = GReaT(llm='EleutherAI/gpt-neo-1.3B', batch_size=32, epochs=25)
```
However, we cannot guarantee that all models will function correctly within this setup. Please open an issue if you need a partially model or even better make a PR. 

As for GPT-3, yes, our algorithm is model-agnostic, meaning it can be used with any generative LLM. However, our framework specifically supports only HuggingFace models. If you wish to use OpenAI's GPT-3, a new implementation will be required.

**Comment by Travisma2233** [comment]
> @Travisma2233
> 
> In general, replacing the model name within the HuggingFace library in GReaT's initialization is typically all you need. For example:
> 
> ```python
> model = GReaT(llm='EleutherAI/gpt-neo-1.3B', batch_size=32, epochs=25)
> ```
> 
> However, we cannot guarantee that all models will function correctly within this setup. Please open an issue if you need a partially model or even better make a PR.
> 
> As for GPT-3, yes, our algorithm is model-agnostic, meaning it can be used with any generative LLM. However, our framework specifically supports only HuggingFace models. If you wish to use OpenAI's GPT-3, a new implementation will be required.

Thanks a lot for your answer. Because my network environment is not good, is there a way to run pytorch_model.bin locally
