### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by onacrame** [kathrinse/be_great#27]
I see the code drops rows with missing data but can this model work with missing data?  Ie can it be adapted to produce missing data in the same way as present in the data

**Comment by unnir** [comment]
Hi, 

Could you please provide more information on your data? 
Regarding the missing values, this is one of the key advantages of our GReaT method - handling missing values and generating them as well.

**Comment by unnir** [comment]
We've made a significant update related to the generation of missing values. Please update your GReaT framework. Now, the model generates realistic samples with missing values by default, if the original dataset contains them.

```sh
pip install -U be-great 
```
