### ISSUE TITLE
Searching for Source Code to Replicate the Paper's Experiments and Evaluations

### ISSUE THREAD

**Issue by sildolfogomes** [kathrinse/be_great#28]
Hi team!

First, I need to say how excited I am about this project and the incredible research you are doing! The article is full of useful information, and it is clear that a lot of effort and dedication went into achieving these results. Congratulations on the incredible work!

I was browsing the repository and getting ready to experiment and play around with the code a bit. I was especially interested in trying to replicate the experiments that you guys did and see if I could recreate the metrics and graphs in the article.

However, I seem to have stumbled over a small snag - I have not been able to locate the corresponding source code. I must have lost it somewhere, or maybe it's not here yet?

I know how big these projects can be, and sometimes it's easy to forget to add everything, but could you guys help me find this code? Furthermore, I believe that not only me, but also other researchers and project enthusiasts would be extremely grateful!

Thanks again for the fantastic job you guys are doing! I look forward to hearing from you and to continue exploring this amazing project.

Best regards, 

Sildolfo Gomes.

**Comment by tleemann** [comment]
Hi, I added code for the metrics that we used in a new branch called ``metrics``. Feel free to check it out. The plots are simple visualizations made with ```matplotlib``` and the ```seaborn``` packages. Hope this helps!

**Comment by sildolfogomes** [comment]
Thank you very much for your effort and time in answering my issue. I promise that any problems or ideas for improvement will be reported.
