### ISSUE TITLE
Breaking the generation loop

### ISSUE THREAD

**Issue by Travisma2233** [kathrinse/be_great#31]
Is there any good way to encounter this situation besides increasing the epoch? My computer performance is limited, and increasing the epoch will greatly prolong the calculation time.
![火柴截图20230714160907778](https://github.com/kathrinse/be_great/assets/83893812/707af501-319f-4eb4-9d2b-0be6d418433d)

**Comment by Madnex** [comment]
Did you try to increase the `max_length `parameter? The default is 100. Depending on the number of features you should increase it quite a bit (e.g. 400). I had the same issue and increasing the parameter worked. If it is too low the model will never generate all the features, hence the loop (trying to generate a new complete sample each iteration).

**Comment by Travisma2233** [comment]
Ok, thank you for your reply, I currently have 14 features, how many features do you have, and what max length do you think is appropriate for 14 features? In addition, since I don't know enough about this code, can I modify it in great.py? Thanks again for your help

**Comment by Madnex** [comment]
You can just set the parameter in the `sample` method: `samples = great.sample(n_samples, k=50, max_length=400`

See the [documentation](https://github.com/kathrinse/be_great/blob/main/docs/api-docs/great.md#method-greatsample).

Easiest is to just try out a few values and see if it can generate samples (and how fast).
