### ISSUE TITLE
Suggestion: Improve sampling speed

### ISSUE THREAD

**Issue by sebffischer** [kathrinse/be_great#33]
First of all, thanks for making this library available. 
When trying to sample large number of samples, the `sample()` code becomes slower. 
I believe this is because of this line: 

https://github.com/kathrinse/be_great/blob/251eb17aa64d7fb7bf42d120a349736f889c6cde/be_great/great_utils.py#L109

I think a speed improvement could be achieved by storing all the dataframes in a list and then concatenating the list of dataframes at the end.

**Comment by unnir** [comment]
Thank you for your interest in our work and the contribution, @sebffischer! 

I believe this issue is similar to https://github.com/kathrinse/be_great/issues/23
