### ISSUE TITLE
Requirements don't allow numpy<1.24

### ISSUE THREAD

**Issue by robsdavis** [kathrinse/be_great#37]
I would love to include this method in our library [synthcity](https://github.com/vanderschaarlab/synthcity).

However, currently we require numpy<1.24 (due to another third party library). Is there a reason that your requirements are for numpy>=1.24.2? I have a few examples working with numpy==1.23.5.

Would you consider allowing older versions of numpy, so that I can more easily add your synthetic data generation method to our library as a new plugin?

Many thanks!

**Comment by unnir** [comment]
Hi @robsdavis 

Thank you for considering including GReaT into your framework. We will be happy if you integrate our approach in the synthcity library. 

Could you please confirm if `numpy>=1.23.5` is acceptable for you?

**Comment by robsdavis** [comment]
Hi @unnir,
Thanks for your response. `numpy>=1.23.5` would definitely work. Thank you for considering changing your requirements.

**Comment by unnir** [comment]
I've updated the requirements. Please let us know if you need further help with the GReaT method.
