### ISSUE TITLE
sampling error

### ISSUE THREAD

**Issue by itime91** [kathrinse/be_great#4]
When training is completed and sampling is performed, the following error occurs. How can I solve it? 
please reply

be_great\great.py:162, in GReaT.sample(self, n_samples, start_col, start_col_dist, temperature, k, max_length, device)
    160 # Convert tokens back to tabular data
    161 text_data = _convert_tokens_to_text(tokens, self.tokenizer)
--> 162 df_gen = _convert_text_to_tabular_data(text_data, df_gen)
    164 # Remove rows with flawed numerical values
    165 for i_num_cols in self.num_cols:

be_great\great_utils.py:91, in _convert_text_to_tabular_data(text, df_gen)
     89         values = f.strip().split(" is ")
     90         if values[0] in columns and not td[values[0]]:
---> 91             td[values[0]] = [values[1]]
     93     df_gen = pd.concat([df_gen, pd.DataFrame(td)], ignore_index=True, axis=0)
     94 return df_gen

IndexError: list index out of range

**Comment by unnir** [comment]
Hi, 

I'm sorry that you are experiencing issues with our framework.  

In order to help you, we need more information about your script and data. Would it be possible to share a sample of your dataset or at least give us some info on it, such as feature names and dataset size (shape) + your code.

**Comment by itime91** [comment]
Thank you for the reply.

It is difficult to share the entire dataset because it is the dataset from the customer for the project, but the used feature names are as follows.
> ['Quality', 'Fob', 'Smls + Welded', 'Code', 'Material', 'Gauge', 'Thickness', 'Length', 'Order quantity', 'Unit weight', 'Unit price', 'Approval date']

And the used dataset is a mixture of category type and numerical type, the sample data is as follows.



Since the error does not always occur,
as in the following, if the number of data generated at once is adjusted to a small size, the error may not occur.

samples_025 = great.sample(100, temperature=0.25, k=10, device='cpu')

------------------------------------------
Also, Is there a case where the generated feature value comes out as a NaN value? 
It seems to happen if there is a lack of learning, but I don't think it's certain.

Thank you for your reply!!



-----Original Message-----

**Comment by unnir** [comment]
Thank you for reporting the issue! 
We will fix it, will keep you updated.  

>as in the following, if the number of data generated at once is adjusted to a small size, the error may not occur.

An interesting observation, you can try to lower the temperature, but it will lead to less diverse synthetic samples... In our experiments, we temperature=0.7 provided the right balance between diversity and stability.  

Another question. For how many epochs have you trained GReaT?
  

@kathrinse, could you please have a look at that?

**Comment by itime91** [comment]
Thank you!
Please reply when the issue is resolved!!

To check creation, only 1 epoch was trained.

-----Original Message-----

**Comment by unnir** [comment]
>To check creation, only 1 epoch was trained.

That explains the weird error, 1 epoch is not enough for the fine-tuning step. I mean, the language model has to get used to your specific data structure. But I'm amazed that you could sample even after one epoch... We need to try it.   

My recommendation is - please train GReaT further. 
Of course, it depends on your problem, but I would _at least_ train it for 40-50 epochs. And I'm sure you will get the most realistic synthetic samples for your dataset :) 

And regarding the issue, we will introduce a more intuitive error message, so it will be clear that further training is needed or something wrong with the data. 
Thank you for reporting it!

**Comment by unnir** [comment]
The new version of our package should provide a more user-friendly error message.
