### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by ayyucedemirbas** [kathrinse/be_great#5]
I tried to install be-great via pip on both google colab and my Mac. However, it says that there is no Python package named be-great.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/8023150/202516180-6d23eee2-fea5-4175-a3bd-1c92d78c300b.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8023150/202516252-45d6011e-a371-41b5-b979-8bc81dbc491e.png">

Then, I tried to download the .whl file from [PyPI](https://pypi.org/project/be-great/#files) and install it.  It also didn't work.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/8023150/202516899-92ae63ff-0175-40c9-a60e-ab9c52e25d9d.png">

I don't know the reason, it looks weird.

Thank you so much!

**Comment by unnir** [comment]
Hi,

My apologies for the difficulties..

It looks like you're using google colab. The issue is that colab still runs on Python 3.7, and GReaT requires at least Python 3.9. Unfortunately, I could not find how to update the python version on colab.

**Comment by ayyucedemirbas** [comment]
Hi,

I created a new conda env with Python 3.9 and it worked. Thank you so much! 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/8023150/202777653-e2672df4-7605-4023-a2ed-cf1ffb8da11e.png">

**Comment by unnir** [comment]
Hi, 

I found a way how to use the GReaT framework on google colab. Here is an example: 
https://github.com/kathrinse/be_great/blob/main/examples/GReaT_colab_example.ipynb
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kathrinse/be_great/blob/main/examples/GReaT_colab_example.ipynb)

You will need to update the Python version there, but it takes less than 5 minutes. Once that is done, you can train the model :)

**Comment by ayyucedemirbas** [comment]
I tried to run this notebook, but it crashes when I tried to restart the runtime.
