### ISSUE TITLE
About the data and model apply

### ISSUE THREAD

**Issue by Kwon-sein** [kathrinse/be_great#58]
Hi, I would like to test the model using the data I have and I have some questions.

The provided 'data' in the paper and GitHub repository uses the sklearn dataset. If I want to augment my own dataset, should I format it as a DataFrame and place it in the 'data = {mydata}?

Additionally, I noticed in a previous issue that it is possible to use an alternative API for the LLM integrated into the model, such as models available on Hugging Face. In this case, should I specify the model path, for example, "meta-llama/Meta-Llama-3-8B-Instruct"?

Thank you.

**Comment by unnir** [comment]
Hi, 

> If I want to augment my own dataset, should I format it as a DataFrame and place it in the 'data = {mydata}?
That is correct, our approach requires feature names and thus it needs pandas DataFrames as input. 

 >In this case, should I specify the model path, for example, "meta-llama/Meta-Llama-3-8B-Instruct"?
Yes, but I recommend to use the base version of this models, such as Llama-3.2-1B, not the instruct

**Comment by Kwon-sein** [comment]
Hi, Thanks a lot for your reply.

Can I leave additional issues if I have any questions? 😅

**Comment by unnir** [comment]
Glad to help.

Sure, just open an issue
