### ISSUE TITLE
The model for GReaT

### ISSUE THREAD

**Issue by ZhangTP1996** [kathrinse/be_great#8]
Thanks for the great work! I am a newbie in NLP so this might be a silly question. I am wondering how to use the GPT-2 model for GReaT? Is it
```
model = GReaT(llm='gpt2', batch_size=32, epochs=50)
```
or are there any examples that run GReaT instead of Distill-GReaT?

**Comment by kathrinse** [comment]
Hey, thanks for your question!

Until now, we only used "distilgpt2" and "gpt2-medium" in our experiments.

But, you should be able to use all the pre-trained models from the HuggingFace Model Hub (https://huggingface.co/models) as large language model (llm) - also "gpt2".
